#!/usr/bin/python
#-*- coding: utf-8 -*-

from ElementoMapa import ElementoMapa

class Contenedor(ElementoMapa):
    def __init__(self):
        self.hijos = []
        self.num=None
        return self
    
    def obtenerHijo(self,pos):
        return self.hijos.index(pos)

    def agregarHijo(self, unEM):
        unEM.padre=self
        self.hijos.append(unEM)
    
    def entrar(self):
        raise NotImplementedError("Subclase debe implementar este metodo.")