#!/usr/bin/python
#-*- coding: utf-8 -*-

from ElementoMapa import ElementoMapa

class Decorator(ElementoMapa):
    def __init__(self):
        self.component=None
    
    def entrar(self):
        return self.component.entrar()
    
    def decorar(self,componente):
        self.component=componente
        
        