#!/usr/bin/python
#-*- coding: utf-8 -*-

from ElementoMapa import ElementoMapa

class HabitacionFuego(ElementoMapa):
    def __init__(self,num,activo):
        self.num=num
        self.norte=None
        self.este=None
        self.oeste=None
        self.sur=None
        self.activo=activo

    def entrar(self):
        if self.activo:
            print('El fuego de la habitación, ',str(self.num) ,'está activo')
        else:
            print('Estas en la habitacion', str(self.num))
