from Juego import Juego

unjuego=Juego()
unjuego.fabricarLaberinto()
unjuego.laberinto4Habitaciones()

print('Habitacion 1')
print ('>Norte: ',unjuego.laberinto.habitaciones[0].norte)
print ('>Oeste: ',unjuego.laberinto.habitaciones[0].oeste)
print ('>Este: ',unjuego.laberinto.habitaciones[0].este)
print ('    >Puerta: ',unjuego.laberinto.habitaciones[0].este.abierta)
print ('>Sur: ',unjuego.laberinto.habitaciones[0].sur)
print ('    >Puerta: ',unjuego.laberinto.habitaciones[0].sur.abierta)

print('Habitacion 2')
print ('>Norte: ',unjuego.laberinto.habitaciones[1].norte)
print ('>Oeste: ',unjuego.laberinto.habitaciones[1].oeste)
print ('    >Puerta: ',unjuego.laberinto.habitaciones[1].oeste.abierta)
print ('>Este: ',unjuego.laberinto.habitaciones[1].este)
print ('>Sur: ',unjuego.laberinto.habitaciones[1].sur)
print ('    >Puerta: ',unjuego.laberinto.habitaciones[1].sur.abierta)
print ('En la habitacion hay: ',unjuego.laberinto.habitaciones[1].obtenerHijo(0))
print ('En el baul hay: ',unjuego.laberinto.habitaciones[1].obtenerHijo(0).obtenerHijo(0))

print('Habitacion 3')
print ('>Norte: ',unjuego.laberinto.habitaciones[2].norte)
print ('    >Puerta: ',unjuego.laberinto.habitaciones[2].norte.abierta)
print ('>Oeste: ',unjuego.laberinto.habitaciones[2].oeste)
print ('>Este: ',unjuego.laberinto.habitaciones[2].este)
print ('    >Puerta: ',unjuego.laberinto.habitaciones[2].este.abierta)
print ('    >Puerta: ',unjuego.laberinto.habitaciones[2].este.activa)
print ('>Sur: ',unjuego.laberinto.habitaciones[2].sur)
print ('En la habitacion hay: ',unjuego.laberinto.habitaciones[2].obtenerHijo(0))
print ('En el baul hay: ',unjuego.laberinto.habitaciones[2].obtenerHijo(0).obtenerHijo(0))

print('Habitacion 4')
print ('>Norte: ',unjuego.laberinto.habitaciones[3].norte)
print ('    >Puerta: ',unjuego.laberinto.habitaciones[3].norte.abierta)
print ('>Oeste: ',unjuego.laberinto.habitaciones[3].oeste)
print ('    >Puerta: ',unjuego.laberinto.habitaciones[3].este.abierta)
print ('    >Puerta: ',unjuego.laberinto.habitaciones[3].este.activa)
print ('>Este: ',unjuego.laberinto.habitaciones[3].este)
print ('>Sur: ',unjuego.laberinto.habitaciones[3].sur)
print ('El fuego de la habitación está encendido?: ',unjuego.laberinto.habitaciones[3].activo)